services:
  backend:
    build:
      context: ./backend
    container_name: devmatch-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: devmatch-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
